version: "3.1"

services:
  httpd-leave_app:
    # image: php-fpm
    hostname: leave_app
    build:
      context: .
      dockerfile: ./images/php-apache/Dockerfile
    image: leave_app:2
    container_name: leave_app
    restart: always
    ports:
      - 8085:80
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./htdocs/leave_app:/var/www/html/
      - ./images/php-apache/config/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./images/php-apache/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  httpd-devfrontend:
    # image: php-fpm
    hostname: devfrontend
    build:
      context: .
      dockerfile: ./images/php-apache/Dockerfile
    image: devfrontend-apache:2
    container_name: devfrontend
    restart: always
    ports:
      - 8083:80
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./htdocs/devfrontend:/var/www/html/
      - ./images/php-apache/config/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./images/php-apache/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  httpd-devbackend:
    # image: php-fpm
    hostname: devbackend
    build:
      context: .
      dockerfile: ./images/php-apache/Dockerfile
    image: devbackend-apache:2
    container_name: devbackend
    restart: always
    ports:
      - 8084:80
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./htdocs/devbackend:/var/www/html/
      - ./images/php-apache/config/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./images/php-apache/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  httpd-ihris:
    # image: php-fpm
    hostname: web-ihris-apache
    build:
      context: .
      dockerfile: ./images/php-apache/Dockerfile
    image: web-ihris-apache:2
    container_name: web-ihris-apache
    restart: always
    ports:
      - 8081:80
    networks:
      - backend
      - frontend
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      REDIS_HOST: redis
    volumes:
      - ./htdocs/ihris:/var/www/html/
      - ./images/php-apache/config/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./images/php-apache/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  httpd-id_card:
    # image: php-fpm
    hostname: web-id_card
    build:
      context: .
      dockerfile: ./images/php-apache/Dockerfile
    image: web-id_card:2
    container_name: web-id_card
    restart: always
    ports:
      - 9090:80
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./htdocs/id_card:/var/www/html/
      - ./images/php-apache/config/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./images/php-apache/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini

  httpd-pcr:
    # image: php-fpm
    hostname: web-pcr-apache
    build:
      context: .
      dockerfile: ./images/php-apache/Dockerfile
    image: web-pcr-apache:2
    container_name: web-pcr-apache
    restart: always
    ports:
      - 8082:80
    networks:
      - backend
      - frontend
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      REDIS_HOST: redis
    volumes:
      - ./htdocs/pcr:/var/www/html/
      - ./images/php-apache/config/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./images/php-apache/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    # docker network create apps-net
    # docker run -d --name php-apache --network apps-net -v C:\Users\fjavalencia\ohrmd_apps\html:/var/www/html/ -p 8081:80 ohrmd_apps-httpd:latest

  db:
    hostname: ohrmd-mariadb
    # image: mariadb:10.4-focal
    build:
      # context: .
      dockerfile: ./images/mariadb/Dockerfile
    image: ohrmd-mariadb-apache:10.4-focal
    container_name: ohrmd-mariadb
    ports:
      - 3369:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    secrets:
      - db_root_password
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/mysql
      # - ./images/mariadb/config/my.cnf:/etc/mysql/conf.d/my.cnf
      # ./config/my.cnf /etc/mysql/conf.d/
      # docker network create apps-net
      # docker run -d --name mariadb --network dev-net -e MARIADB_ROOT_PASSWORD=superhr2023 -v db-data:/var/lib/mysql mariadb:10.6

  phpmyadmin:
    hostname: ohrmd-phpmyadmin
    container_name: ohrmd-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 254M
    links:
      - db:db
    depends_on:
      - db
    networks:
      - backend
      - frontend

    # docker run -d --name phpmyadmin --network apps-net -e PMA_ARBITRARY=1 -p 8080:80 phpmyadmin

  redis:
    container_name: "ihris-redis"
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - "ihris-redis:/data"
    networks:
      - backend
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  backend:
  frontend:

volumes:
  dbdata:
  ihris-redis:
    driver: local

secrets:
  db_root_password:
    file: db_root_password.txt
